name: gen-lockfile

on:
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Genera package-lock.json SIN instalar (sólo resuelve y escribe el lock)
      - name: Generate lockfile
        run: npm install --package-lock-only

      - name: Upload lockfile
        uses: actions/upload-artifact@v4
        with:
          name: package-lock
          path: package-lock.json
          if-no-files-found: error
